## Accessing, changing specific elements, rows, columns, ect

In [2]:
import numpy as np

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

### Getting a specific element [row, column]

In [15]:
a[1, 5], a[-1, -2], a[1][5]

(13, 13, 13)

### Getting a specific row [row]

In [17]:
a[0, :], a[0]

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7]))

### Getting a specific column

In [19]:
a[:, 4]

array([ 5, 12])

### Using [starter_index:end_index:step_index]

In [26]:
a[0, 1:6:2]

array([2, 4])