## Initializing Different Arrays


In [1]:
import numpy as np

#### Filling ndarrays with zeros and ones

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Filling ndarrays with a certain value

In [6]:
np.full(10, 100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [7]:
np.full((2,3,3), 9)

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

#### Filling a ndarray with a shape previously used

In [8]:
a = np.array([[1, 3, 4], [4, 5, 6], [7, 8, 9]])
np.full_like(a, 999)

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

#### Filling a ndarray with random decimal values between 0 and 1

In [9]:
np.random.rand(5)

array([0.39747234, 0.90042943, 0.67331726, 0.25785307, 0.128616  ])

In [10]:
np.random.rand(2,5)

array([[0.03712303, 0.71510006, 0.64080286, 0.65721386, 0.3585407 ],
       [0.23546167, 0.09840212, 0.66305982, 0.9556793 , 0.87593172]])

##### Filling a previously used chape with random values between 0 and 1

In [11]:
np.random.random_sample(a.shape)

array([[0.29305606, 0.32016452, 0.23140375],
       [0.9996318 , 0.65184662, 0.43616257],
       [0.2625848 , 0.84596778, 0.10669673]])

#### Filling a ndarray with random integer values

In [12]:
np.random.randint(4, size=(3,2))

array([[0, 0],
       [0, 0],
       [3, 3]])

In [13]:
np.random.randint(0, 8, size=a.shape)

array([[1, 5, 7],
       [5, 0, 1],
       [4, 5, 7]])

#### Creating an identity matrix

In [14]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Repeating arrays 

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [16]:
arr = np.array([[1, 2, 3, 4, 5, 6]])
np.repeat(arr, 3, axis=0) # repeating arr 3x 

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

### Challenge: Trying to recreate the following matrix

|1|1|1|1|1|
|-|-|-|-|-|
|1|0|0|0|1|
|1|0|9|0|1|
|1|0|0|0|1|
|1|1|1|1|1|

In [17]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
arr[1, 1:4:1] = 0
arr[2, 1:4:2] = 0
arr[3, 1:4:1] = 0
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays

In [21]:
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [22]:
b = a
b

array([1, 2, 4])

In [23]:
b[0] = 99
a, b

(array([99,  2,  4]), array([99,  2,  4]))

In this case, both variables a and b point to the same slot of memory so, if you change one, you change both. To make a copy, you need to use `.copy()`

In [24]:
a = np.array([1, 2, 3, 4])
b = a.copy()
b[0] = 100
a, b

(array([1, 2, 3, 4]), array([100,   2,   3,   4]))

### Mathematics

In [37]:
a = np.array([10, 20, 30, 40, 50])

In [34]:
a + 10

array([20, 30, 40, 50, 60])

In [38]:
a += 10
a

array([20, 30, 40, 50, 60])

In [28]:
a - 5

array([ 5, 15, 25, 35, 45])

In [29]:
a * 2

array([ 20,  40,  60,  80, 100])

In [32]:
a / 5

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
a ** 2

array([ 400,  900, 1600, 2500, 3600])

In [40]:
b = np.array([1, 2, 1, 2, 1])
a + b

array([21, 32, 41, 52, 61])

`sin`, `cos` and `tan` of np arrays

In [42]:
np.sin(a), np.cos(a), np.tan(a)

(array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485, -0.30481062]),
 array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603, -0.95241298]),
 array([ 2.23716094, -6.4053312 , -1.11721493, -0.27190061,  0.32004039]))

#### Linear Algebra

In [44]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

Multiplying matrices

In [46]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

Finding the determinant of a matrix

In [47]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [50]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

1

In [55]:
np.max(stats)

6

In [60]:
np.max(stats, axis=0)

array([4, 5, 6])

In [61]:
np.max(stats, axis=1)

array([3, 6])

In [63]:
np.max(stats, axis=0).sum()

15

In [64]:
np.max(stats, axis=1).sum()

9

### Reorganizing arrays

In [65]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Using `reshape(number_of_lines_wanted, number_of_columns_wanted)`

In [66]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [67]:
after = before.reshape((4, 2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Vertically stacking vectors

In [70]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2]), np.vstack([v2, v1])

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[5, 6, 7, 8],
        [1, 2, 3, 4]]))

In [71]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Horizontal stacking vectors

In [72]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])