## Initializing Different Arrays


In [1]:
import numpy as np

#### Filling ndarrays with zeros and ones

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Filling ndarrays with a certain value

In [8]:
np.full(10, 100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
np.full((2,3,3), 9)

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]])

#### Filling a ndarray with a shape previously used

In [11]:
a = np.array([[1, 3, 4], [4, 5, 6], [7, 8, 9]])
np.full_like(a, 999)

array([[999, 999, 999],
       [999, 999, 999],
       [999, 999, 999]])

#### Filling a ndarray with random decimal values between 0 and 1

In [19]:
np.random.rand(5)

array([0.61900299, 0.70784853, 0.93280286, 0.0354817 , 0.49816207])

In [16]:
np.random.rand(2,5)

array([[0.15679488, 0.10160968, 0.66484905, 0.93115691, 0.87288635],
       [0.87108178, 0.22533258, 0.31447039, 0.08527168, 0.05620148]])

##### Filling a previously used chape with random values between 0 and 1

In [20]:
np.random.random_sample(a.shape)

array([[0.44194699, 0.87434706, 0.94166843],
       [0.04533632, 0.23754384, 0.04654649],
       [0.08069681, 0.43452409, 0.2829451 ]])

#### Filling a ndarray with random integer values

In [21]:
np.random.randint(4, size=(3,2))

array([[3, 3],
       [3, 2],
       [1, 0]])

In [26]:
np.random.randint(0, 8, size=a.shape)

array([[0, 2, 7],
       [2, 5, 5],
       [3, 1, 2]])

#### Creating an identity matrix

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Repeating arrays 

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.repeat(arr, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [33]:
arr = np.array([[1, 2, 3, 4, 5, 6]])
np.repeat(arr, 3, axis=0) # repeating arr 3x 

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

### Challenge: Trying to recreate the following matrix

|1|1|1|1|1|
|-|-|-|-|-|
|1|0|0|0|1|
|1|0|9|0|1|
|1|0|0|0|1|
|1|1|1|1|1|

In [72]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
arr[1, 1:4:1] = 0
arr[2, 1:4:2] = 0
arr[3, 1:4:1] = 0
arr[2,2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])